# Generated by Django 3.1.2 on 2021-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='video',
            name='licenseUrl',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='videoId',
            field=models.IntegerField(default=0),
        ),
    ]
