# Generated by Django 3.1.2 on 2021-01-20 13:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210119_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='licenseUrl',
            new_name='license_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='videoId',
            new_name='video_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.AddField(
            model_name='video',
            name='speakers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=['test'], size=8),
            preserve_default=False,
        ),
    ]
