# Generated by Django 3.1.2 on 2021-01-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210120_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='event',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='viewed_count',
            field=models.IntegerField(default=0),
        ),
    ]
