# Generated by Django 3.1.2 on 2021-01-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210120_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
