# Generated by Django 3.1.2 on 2021-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='contentJson',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='videoId',
            field=models.IntegerField(default=0),
        ),
    ]
