# Generated by Django 3.1.2 on 2021-01-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subtitles', '0002_auto_20210119_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='contentJson',
            new_name='content_json',
        ),
        migrations.RenameField(
            model_name='subtitle',
            old_name='videoId',
            new_name='video_id',
        ),
    ]
