version: "3.8"
services:
  postgres:
    image: "postgres:13.1"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=subtitles
      - POSTGRES_DB=subtitledb
volumes:
  postgres: